apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-user-deployment
  namespace: cvalyze
  labels:
    app: cv-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-user
  template:
    metadata:
      labels:
        app: cv-user
      annotations:         
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: cv-user
          image: afzal23/cv_user_service:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: user-env
          