apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-gateway-deployment
  namespace: cvalyze
  labels:
    app: cv-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-gateway
  template:
    metadata:
      labels:
        app: cv-gateway
    spec:
      containers:
        - name: cv-gateway
          image: afzal23/cv_gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gateway-env
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
