apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-gateway-ingress
  namespace: cvalyze
spec:
  ingressClassName: nginx
  rules:
    - host: cvalyze.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-gateway
                port:
                  number: 8000
