apiVersion: v1
kind: Service
metadata:
  name: cv-gateway
  namespace: cvalyze
  labels:
    app: cv-gateway
spec:
  selector:
    app: cv-gateway
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
