apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-etl-deployment
  namespace: cvalyze
  labels:
    app: cv-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-etl
  template:
    metadata:
      labels:
        app: cv-etl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8002"
    spec:
      serviceAccountName: cv-etl-sa
      containers:
        - name: cv-etl
          image: afzal23/cv_etl_service:v16
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
              name: http
          envFrom:
            - configMapRef:
                name: etl-env
          resources:
            requests:
              cpu: "150m"      # Reduced from 1000m
              memory: "384Mi"  # Reduced from 2Gi
            limits:
              cpu: "400m"      # Reduced from 1500m
              memory: "768Mi"    # Reduced from 3Gi
          