apiVersion: v1
kind: ServiceAccount
metadata:
  name: cv-etl-sa
  namespace: cvalyze
  annotations:
    iam.gke.io/gcp-service-account: cvalyze-service-acc-50@project-72dfbe56-9a82-4b81-a1a.iam.gserviceaccount.com