apiVersion: v1
kind: Service
metadata:
  name: cv-etl-service
  namespace: cvalyze
  labels:
    app: cv-etl
spec:
  selector:
    app: cv-etl
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
